application: workmanager-2016
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/signup
  script: api.signup.app

- url: /api/loginManager
  script: api.login.app

- url: /api/loginCode
  script: api.login.app

- url: /api/getuserinfo
  script: api.info.app

- url: /api/getcustomerinfo
  script: api.info.app

- url: /api/getusercustomers
  script: api.info.app

- url: /api/addcustomer
  script: api.addCustomer.app

- url: /api/updatecustomer
  script: api.updateCustomer.app

- url: /api/addcustomerhours
  script: api.updateCustomer.app

- url: /api/resetcustomerhours
  script: api.updateCustomer.app

- url: .*
  script: main.app
  

libraries:
- name: webapp2
  version: "2.5.2"
